### ISSUE TITLE
Rust code is not unicode-safe

### ISSUE THREAD

**Issue by masklinn** [zsiciarz/rust-ffi-stringtools#4]
Altering one of the input scripts to send properly encoded non-ascii data (e.g. "Iñtërnâtiônàlizætiøn") leads to a fatal panic:

```
thread '<unnamed>' panicked at 'index 1 and/or 2 in `Iñtërnâtiônàlizætiøn` do not lie on character boundary', ../src/libcore/str/mod.rs:1284
fatal runtime error: Could not unwind stack, error = 5
```

**Comment by zsiciarz** [comment]
Hi, thanks for the report!
 I haven't really noticed that [matches()](https://doc.rust-lang.org/std/primitive.str.html#method.matches) was stabilized in 1.3. That is cool, so now we can get rid of the ugly loop and fix the non-ascii issue.
